### ISSUE TITLE
dbStructures merge issue

### ISSUE THREAD

**Issue by gmhhope** [shuzhao-li/JMS#13]
There is a merge conflict spot at commit (https://github.com/shuzhao-li/JMS/commit/297dea56801dfc97719d3ea03ccedda58fe96cd1). Needs to remove the problematic one.

I looked into it and I think it is more likely should keep the `HEAD` one and discard the one from `88a17cb7d9f78fc4b563e031e55f219a2df0b35f`. But it is probably better to have you checked and correct it directly. @shuzhao-li

**Comment by shuzhao-li** [comment]
Okay, fixed.
