### ISSUE TITLE
An exceptional compound table which doesn't fit with mass inference rule

### ISSUE THREAD

**Issue by gmhhope** [shuzhao-li/JMS#2]
Generate an exceptional compound table which doesn't fit with mass inference rule. 

## Strategies
- See https://github.com/gmhhope/master-compound-table/issues/21

**Comment by jmmitc06** [comment]
The link provided is now deprecated. I assume though that this was the empCpd table that had the entry that was off by the mass of one hydrogen? 

I'm going to close this issue for a few reasons. First, JMS is for annotation of user-provided masses and formulas, if an incorrect mass is provided it will get incorrect annotations but this is not JMSs responsibility. Second, we have not been able to replicate the issue that led to the creation of that problematic empCpd; however, lets be on the look out for more examples so we can pin down the issue in Khipu.
