### ISSUE TITLE
JMS's name was used in other anaconda pkg

### ISSUE THREAD

**Issue by gmhhope** [shuzhao-li/JMS#3]
JMS's name was used in other anaconda pkg (probably Java message service) as follows:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Input In [10], in <cell line: 1>()
----> 1 from jms import adjust_charge_in_formula

ImportError: cannot import name 'adjust_charge_in_formula' from 'jms' (/Users/gongm/opt/anaconda3/lib/python3.8/site-packages/jms/__init__.py)
```
Change the name of the folder jms to `jms_metabolomics` fix the issue temporarily.

**Comment by shuzhao-li** [comment]
Could you pls verify what is /Users/gongm/opt/anaconda3/lib/python3.8/site-packages/jms/?

**Comment by gmhhope** [comment]
I found out that this is a copy of `jms`, which probably I pasted before into the anaconda library. Close the issue accordingly.
